### PR TITLE
Update config.mk

### PR DESCRIPTION
**Pull request by ghost**
few devices cant be compiled because of these

### CODE REVIEW

**Comment by aditheking** [comment]
-_- ?

**Comment by ghost** [comment]
Please?

**Comment by HridayHS** [comment]
What please ?
Can you be more specific about changes ?

**Comment by ghost** [comment]
You *cannot* build for older devices like LG G2, LG G, HTC One M7 etc. with the lines I removed here

**Comment by aditheking** [comment]
("-_-)

**Pull request closed without merging**
